baseurl = "https://nervous-kalam-14020d.netlify.app"
languageCode = "en-us"
languageLang = "en"
title = "My new Victor-Hugo site"


# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[Params]
    staticman_api = "https://rhcomments.herokuapp.com/v2/entry/port949/victor-hugo-2020/master/comments"
